# Generated by Django 3.0.5 on 2020-09-21 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='Attendencein',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='Attendenceout',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
